services:
  - type: web
    name: pcpartpicker-api
    runtime: node
    rootDir: backend
    startCommand: npm start
    buildCommand: npm install
    envVars:
      - key: MONGO_URI
        sync: false
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        sync: false

  - type: static_site
    name: pcpartpicker-web
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://pcpartpickerapi.onrender.com
