version: "1"
projects:
- name: MyPCParts
  environments:
  - name: Production
    services:
    - type: web
      name: MyPCParts-WebApp
      runtime: node
      repo: https://github.com/RafaelParaisoBSU/PCPartPicker-Website-TOMWEBA1
      plan: free
      envVars:
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      - key: MONGO_URI
        sync: false
      region: singapore
      buildCommand: npm run install-all && npm run build
      startCommand: cd backend && NODE_ENV=production node server.js
      autoDeployTrigger: commit
